### ISSUE TITLE
Crashed after fresh install the first time

### ISSUE THREAD

**Issue by timeakesmarky** [MatteCarra/AccA#32]
ACC App crashed when I first installed and opened it, worked fine after that:
```
Process: mattecarra.accapp
Flags: 0x38e8be44
Package: mattecarra.accapp v12 (1.0.8)
Build: google/hammerhead/hammerhead:6.0.1/M4B30Z/3437181:user/release-keys

java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {mattecarra.accapp/mattecarra.accapp.activities.MainActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
  at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
  at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
  at android.app.ActivityThread.-wrap16(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
  at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2080)
  at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2106)
  at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:683)
  at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:637)
  at mattecarra.accapp.activities.MainActivity.loadFragment(MainActivity.kt:159)
  at mattecarra.accapp.activities.MainActivity.onNavigationItemSelected(MainActivity.kt:139)
  at com.google.android.material.bottomnavigation.BottomNavigationView$1.onMenuItemSelected(BottomNavigationView.java:204)
  at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
  at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
  at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
  at com.google.android.material.bottomnavigation.BottomNavigationView.setSelectedItemId(BottomNavigationView.java:405)
  at mattecarra.accapp.activities.MainActivity.initUi(MainActivity.kt:276)
  at mattecarra.accapp.activities.MainActivity.onRequestPermissionsResult(MainActivity.kt:121)
  at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6582)
  at android.app.Activity.dispatchActivityResult(Activity.java:6460)
  at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
  ... 10 more
```

**Comment by MatteCarra** [comment]
This issue should not happen again
